In [1]:
print("Hello")

Hello

In [28]:
# # =========================
# 1. IMPORTS
# =========================
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd
import json
from sentence_transformers import SentenceTransformer
import numpy as np
import joblib

In [3]:


# =========================
# 2. LOAD DATA
# =========================
with open("chunks.json", "r", encoding="utf-8") as f:
    data = json.load(f)

print(f"Loaded chunks: {len(data)}")

Loaded chunks: 821

In [4]:

# =========================
# 3. LOAD MODEL
# =========================
MODEL_NAME = "nomic-ai/nomic-embed-text-v1.5"
model = SentenceTransformer(MODEL_NAME, trust_remote_code=True)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
<All keys matched successfully>

In [5]:

# =========================
# 4. EMBEDDING FUNCTION
# =========================
def create_embeddings_batch(texts):
    """
    Efficient batch embedding using SentenceTransformers.
    """
    return model.encode(
        texts,
        batch_size=32,
        show_progress_bar=True,
        normalize_embeddings=True  # important for cosine similarity search
    )

In [6]:

# =========================
# 5. PROCESS IN BATCHES
# =========================
BATCH_SIZE = 32

chunks_with_vectors = []

for i in range(0, len(data), BATCH_SIZE):
    batch = data[i:i + BATCH_SIZE]

    texts = [chunk["text"] for chunk in batch]

    embeddings = create_embeddings_batch(texts)

    for chunk, emb in zip(batch, embeddings):
        chunk["embedding"] = emb.tolist()  # numpy → JSON serializable
        chunks_with_vectors.append(chunk)

    print(f"Processed {min(i + BATCH_SIZE, len(data))}/{len(data)}")

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Processed 32/821

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Processed 64/821

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Processed 96/821

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Processed 128/821

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Processed 160/821

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Processed 192/821

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Processed 224/821

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Processed 256/821

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Processed 288/821

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Processed 320/821

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Processed 352/821

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Processed 384/821

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Processed 416/821

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Processed 448/821

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Processed 480/821

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Processed 512/821

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Processed 544/821

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Processed 576/821

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Processed 608/821

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Processed 640/821

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Processed 672/821

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Processed 704/821

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Processed 736/821

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Processed 768/821

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Processed 800/821

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Processed 821/821

In [7]:

# =========================
# 6. SAVE OUTPUT
# =========================
with open("chunks_with_vectors.json", "w", encoding="utf-8") as f:
    json.dump(chunks_with_vectors, f, ensure_ascii=False)

print("Embedding pipeline complete 🚀 File saved: chunks_with_vectors.json")

Embedding pipeline complete 🚀 File saved: chunks_with_vectors.json

In [8]:
df=pd.read_json("chunks_with_vectors.json")

In [9]:
def create_question_embedding(question):
    return model.encode(
        question,
        normalize_embeddings=True
    )

incoming_query=input("Ask a question: ")
question_embedding = create_question_embedding(incoming_query)

In [10]:
question_embedding

array([ 1.60613656e-02,  5.06979190e-02, -1.47457793e-01, -8.45390856e-02,
        5.85887395e-02,  2.72731185e-02, -1.35218864e-02, -5.82456738e-02,
       -3.51754576e-02, -1.00840211e-01,  4.53865575e-03,  6.37285784e-02,
        1.56339630e-01, -3.41442265e-02, -3.98536399e-02,  2.72600055e-02,
       -1.06748268e-01, -7.80526698e-02, -1.61011592e-02, -3.31018632e-03,
        1.12934904e-02, -3.36836465e-02,  1.72268674e-02, -9.44340602e-03,
        1.03903830e-01,  1.65266283e-02, -8.42695218e-03, -3.68254557e-02,
        1.38082933e-02,  4.05120291e-02, -2.51095160e-03,  6.09754808e-02,
        1.82048250e-02,  2.01884434e-02, -5.61747402e-02, -4.13464718e-02,
       -6.85300678e-02,  6.99822512e-03,  3.16956379e-02, -2.43851077e-03,
       -5.33795133e-02,  2.71599311e-02, -1.39294798e-02, -2.91349310e-02,
        5.66440932e-02, -1.84382452e-03, -2.45875400e-02, -5.60231507e-02,
        5.44222035e-02, -3.17638554e-02, -1.62492376e-02, -1.52866058e-02,
        2.16276627e-02,  5.52676767e-02,  3.10803223e-02, -3.02556828e-02,
       -2.04281546e-02,  1.13604637e-02,  5.45446435e-03, -8.22456256e-02,
        8.02331939e-02,  9.45237949e-02, -7.60828331e-02,  1.88330002e-02,
        3.89125608e-02, -4.47709076e-02, -1.38358772e-02, -1.22650880e-02,
        2.01699231e-02, -8.88935849e-02,  3.92456613e-02,  6.11917628e-03,
        2.39207577e-02, -3.84836495e-02, -2.66395900e-02, -5.84867690e-03,
       -7.60854315e-03, -1.98192671e-02, -5.03072292e-02,  3.23126186e-03,
        2.09179912e-02, -9.65640042e-03,  3.13317925e-02, -2.08793785e-02,
        4.77686375e-02,  6.92436937e-03, -4.93126102e-02, -3.32922791e-03,
       -1.00429663e-02,  4.45375331e-02, -1.98868383e-02,  1.67938769e-02,
        3.56964804e-02, -2.91871447e-02, -5.41343838e-02,  1.34238442e-02,
        3.63368019e-02, -1.44692883e-03, -8.38302169e-03, -1.96182765e-02,
       -7.26190060e-02, -1.60351265e-02, -7.70321442e-03, -1.86829432e-03,
        2.40595359e-02,  3.11311577e-02,  4.37617302e-03,  3.22303437e-02,
       -2.09962521e-02, -5.58981439e-03, -2.40963176e-02,  4.42143269e-02,
       -8.23908206e-03, -8.27879924e-03,  2.51384662e-03, -2.38736463e-03,
        7.83216115e-03, -5.53816184e-02, -3.62876393e-02, -2.08125692e-02,
        1.08198449e-02, -2.28952169e-02,  2.08964082e-03,  3.98623273e-02,
       -5.44618294e-02, -5.80006791e-03, -4.40580174e-02,  1.46548832e-02,
       -2.11816560e-02,  3.22093703e-02, -3.11099854e-03, -5.53259216e-02,
       -6.59706965e-02, -1.20009072e-02,  1.59908389e-03,  5.23996167e-02,
       -3.65830287e-02, -3.38107236e-02,  1.29799172e-02,  2.88042054e-02,
        2.46512294e-02,  4.05191928e-02, -7.15052783e-02,  2.57323701e-02,
        1.96481533e-02, -1.66128706e-02,  5.18825166e-02,  4.59675444e-03,
       -6.90454617e-03, -5.00457473e-02,  5.48039936e-02,  4.56491411e-02,
        1.76058505e-02, -5.39808646e-02, -1.21350575e-03, -2.18792446e-02,
        2.48097756e-04,  5.55322841e-02,  6.34602830e-02,  1.08145000e-02,
        8.19266587e-02,  7.26724789e-03, -4.18794081e-02,  3.37944068e-02,
       -1.25964098e-02, -2.80174613e-02,  7.90034304e-04,  2.01898851e-02,
        4.44963127e-02,  3.52469124e-02, -4.27911915e-02, -3.42400782e-02,
        3.75095904e-02,  4.05624881e-03,  2.35082116e-02, -7.29750330e-03,
       -5.90281226e-02, -4.16803472e-02,  2.71006711e-02, -4.83872406e-02,
       -1.35350777e-02, -5.74572459e-02, -4.95435484e-03,  4.37487885e-02,
        9.85818170e-03, -2.03644428e-02,  2.97944788e-02,  1.59239564e-02,
       -7.68280122e-03, -2.92883553e-02,  7.18662655e-03,  4.55687172e-04,
       -1.33018335e-02, -2.80681960e-02,  3.29002663e-02, -9.69025213e-03,
        1.35538941e-02,  2.83275656e-02,  4.89008464e-02, -3.14955004e-02,
       -1.86181478e-02,  2.89192218e-02, -5.66683747e-02,  5.19775134e-03,
       -3.87044065e-02,  3.12187579e-02, -3.81589606e-02,  1.27363782e-02,
       -6.69352524e-03,  4.33972254e-02,  7.55005330e-02,  8.70991219e-03,
        1.56124472e-03, -1.50655322e-02, -7.90296774e-03, -3.62401344e-02,
       -5.28682582e-02, -3.82455364e-02,  2.12285314e-02,  3.46985981e-02,
       -4.39497083e-02, -3.55564505e-02,  6.87543154e-02,  3.35614420e-02,
        5.53890876e-02,  1.95733346e-02, -2.82234419e-02, -4.77682948e-02,
       -7.61255110e-03, -1.91584765e-03, -2.12401785e-02, -8.55323076e-02,
        2.54179053e-02, -8.58709216e-03,  2.10273508e-02,  3.67898904e-02,
        3.73807549e-02,  3.24861775e-03,  6.08859099e-02,  2.31625251e-02,
       -3.42030339e-02,  1.44582074e-02, -1.69782937e-02,  2.47823074e-02,
       -2.51542069e-02,  5.17171100e-02,  2.83600707e-02, -2.45314348e-03,
       -2.83328407e-02, -2.75120679e-02,  1.87616851e-02, -1.49716930e-02,
        1.09535661e-02,  2.84379534e-02,  3.14469151e-02, -3.06736361e-02,
       -2.56425813e-02,  7.16665480e-03,  2.34178994e-02,  8.08157492e-03,
        4.00853790e-02, -2.51613799e-02,  3.52334604e-02, -5.31468093e-02,
        3.74845825e-02,  9.53213370e-04,  1.00752451e-02, -5.89228375e-03,
        3.92088463e-04, -2.90683918e-02,  3.60820256e-02,  1.03205685e-02,
       -3.50985955e-03, -2.33289017e-03,  7.59609509e-03,  3.88890728e-02,
       -6.65144762e-03,  3.04275043e-02, -9.97698773e-03, -1.88794881e-02,
       -1.14565892e-02,  2.30405089e-02, -5.67836389e-02,  8.66364804e-04,
       -7.11430237e-03,  8.30706060e-02,  6.56717867e-02, -2.40504295e-02,
        3.47378887e-02,  5.26384935e-02,  4.46475595e-02, -3.82051989e-02,
       -5.27764261e-02,  1.66096073e-02,  4.44443012e-03,  2.24851463e-02,
        5.08804359e-02,  2.64714062e-02,  5.75664937e-02, -5.20501696e-02,
        1.21901231e-02,  4.43598889e-02,  6.79230317e-02,  6.67436467e-03,
        2.71671042e-02, -1.27410879e-02,  3.27816308e-02, -4.07044850e-02,
       -1.18762096e-02, -4.59872112e-02, -2.12013964e-02, -6.74015423e-03,
       -1.74709782e-02,  3.06111872e-02, -3.23376656e-02,  4.05756347e-02,
        1.08316187e-02,  1.69040877e-02,  4.28112336e-02, -3.64137702e-02,
        4.97589186e-02, -5.20921014e-02, -1.77923050e-02, -4.10548858e-02,
       -2.60348059e-03,  6.15039058e-02, -5.22582652e-03,  1.82052646e-02,
       -1.69085879e-02, -4.41761548e-03,  3.82065065e-02, -4.11645994e-02,
       -4.04342934e-02, -5.65771684e-02, -5.31483367e-02,  6.20647967e-02,
        4.60915314e-03, -2.13853400e-02,  4.65490622e-03,  4.40839976e-02,
       -1.25705311e-02,  2.05073971e-02, -3.02446657e-03, -6.24795854e-02,
        1.53279062e-02,  3.58627997e-02, -3.13690640e-02, -5.46583571e-02,
        3.27863581e-02,  4.59429547e-02, -3.59754153e-02,  2.94925869e-02,
       -2.47636829e-02,  1.53523032e-02, -2.00514384e-02,  4.49331198e-03,
        2.15572305e-02,  3.72567326e-02,  2.87501663e-02,  4.24237596e-03,
       -1.15234172e-02,  1.58879664e-02, -5.38837239e-02,  3.58095998e-03,
       -1.77619867e-02, -2.80882232e-02,  5.03089577e-02,  4.93628904e-04,
        1.88681930e-02,  3.42580723e-03, -2.67484318e-02, -1.35449991e-02,
        1.48275737e-02,  4.22029532e-02,  3.97002697e-02, -3.33293714e-02,
       -1.06758796e-01,  5.96285192e-03, -1.58260372e-02,  5.58556765e-02,
        2.70416941e-02,  6.56579807e-02,  3.94126214e-02, -3.56143974e-02,
        2.03618389e-02, -1.66193284e-02, -2.75612026e-02, -1.83904415e-03,
        4.26066434e-03,  2.01724074e-03,  1.57973133e-02, -2.46698875e-02,
       -5.40798120e-02,  9.72511433e-03, -5.97702991e-03, -4.34142612e-02,
       -5.56338355e-02,  5.66799603e-02,  1.76327694e-02, -1.66063774e-02,
       -1.76720787e-02, -2.90196650e-02, -3.35425660e-02, -4.05728407e-02,
       -3.38696130e-02,  6.65785521e-02, -1.63760185e-02, -6.71322271e-02,
        3.39699052e-02,  2.85269246e-02,  2.74419282e-02,  2.03799587e-02,
       -1.23251425e-02, -3.74583416e-02,  1.52282929e-02,  3.47472169e-02,
        1.53306639e-02, -3.30780540e-03, -3.86678651e-02,  2.32558828e-02,
        7.46384114e-02,  7.13831512e-03,  5.94571885e-03,  6.06025686e-04,
       -2.27429457e-02,  3.32426950e-02,  5.11307642e-02,  6.48155808e-02,
       -4.69073467e-02, -4.16457094e-02,  3.23774815e-02, -2.44549010e-03,
        3.61003983e-03,  7.44634047e-02, -4.66499142e-02,  3.66980359e-02,
        5.15996404e-02,  1.76449195e-02, -8.87483805e-02,  8.05967152e-02,
       -9.48104914e-03, -5.85307032e-02,  2.77714022e-02,  2.82719377e-02,
        2.65200250e-02,  8.86312500e-02,  2.02711429e-02, -5.53947538e-02,
       -5.73634692e-02,  9.12250578e-02, -2.57147616e-03,  4.30762842e-02,
       -9.17693507e-03,  5.97376041e-02,  8.86810496e-02,  8.03232193e-03,
        6.72353851e-03,  1.51415849e-02, -1.39743965e-02,  3.41146588e-02,
       -1.56381764e-02, -4.54658754e-02, -2.85421535e-02,  2.19272133e-02,
       -1.78567115e-02, -3.25800925e-02,  1.12677435e-03, -7.08292425e-02,
        4.28948924e-02,  2.41344888e-02, -5.53033836e-02,  3.32994163e-02,
        2.61253025e-02, -1.00200484e-02,  3.01561747e-02, -1.45596843e-02,
       -2.90817004e-02, -3.52497250e-02,  2.77495366e-02,  1.74824223e-02,
        4.53983434e-02, -2.41057687e-02, -4.36430331e-03, -3.19389440e-02,
       -1.07227517e-02,  2.78865229e-02,  2.68312134e-02, -2.76340302e-02,
        1.19627323e-02, -6.10984955e-03,  2.05075764e-03, -2.72399876e-02,
        8.85690153e-02, -2.82407869e-02, -2.20182464e-02,  5.84967900e-03,
       -1.87597889e-02, -4.16067764e-02, -2.59302277e-02, -3.05276588e-02,
       -3.82081768e-03,  3.40431067e-03,  2.63652741e-03,  2.22703703e-02,
        3.72684672e-02,  8.72695073e-03,  4.50200029e-02, -6.94257021e-02,
       -3.68709601e-02, -9.58150532e-03, -5.60088046e-02,  5.57862297e-02,
        6.30494356e-02,  6.10741600e-02,  1.37698986e-02, -5.08191548e-02,
        1.36644924e-02,  4.35120426e-02, -2.40330398e-03, -3.28624919e-02,
       -4.79001142e-02, -3.78453955e-02,  1.22378918e-03,  3.06786858e-02,
       -6.27764734e-04, -7.63744535e-03, -3.23265269e-02, -2.01689508e-02,
        8.87419935e-03,  3.00886091e-02,  4.20613848e-02, -3.93240061e-03,
       -3.39942575e-02, -4.14219573e-02,  8.67400132e-03, -3.55194807e-02,
       -5.27199283e-02,  4.24390323e-02,  2.92607844e-02,  6.81974962e-02,
       -1.96947549e-02,  4.08370569e-02,  1.18695581e-02, -8.12101830e-03,
       -3.26314382e-02, -4.09825593e-02,  1.35684591e-02, -5.11150574e-03,
        2.33126190e-02, -3.74226682e-02, -1.63304433e-02,  9.41685960e-03,
       -5.36757242e-03, -3.05463448e-02, -2.70886086e-02, -1.59401782e-02,
       -3.11876480e-02, -8.26541707e-03, -6.91919681e-03, -3.11461706e-02,
        1.15063433e-02,  2.90699154e-02,  1.00284182e-02,  1.55728660e-03,
       -1.84261259e-02, -7.81409442e-03, -1.72005352e-02,  8.69461615e-03,
        4.41661775e-02, -3.15600894e-02, -5.25456714e-03, -4.59913872e-02,
       -3.26774968e-03, -7.54969369e-04,  3.33028031e-04,  2.60974467e-02,
        3.64450403e-02, -2.08126344e-02, -2.89816391e-02, -3.55376787e-02,
        6.27598166e-02, -4.86031100e-02,  2.46828236e-02,  1.83685571e-02,
       -1.87587999e-02,  1.10265175e-02, -1.55848153e-02,  2.44460464e-03,
        6.62247417e-03, -4.11290005e-02, -7.24920034e-02,  4.00094576e-02,
       -2.47159391e-03,  6.06543850e-03, -3.82108875e-02,  2.94198878e-02,
       -2.97683459e-02,  4.56153899e-02,  1.33653893e-03, -5.35866432e-02,
       -1.38742989e-03,  3.61707285e-02,  2.86417138e-02,  1.00902962e-02,
        1.88629031e-02,  3.35823521e-02,  4.27441895e-02, -1.08300373e-02,
       -4.45051529e-02, -3.26009989e-02,  5.90994991e-02, -1.82811171e-02,
       -8.30147266e-02,  4.48796153e-03,  2.05427930e-02, -3.48760374e-02,
        1.33736813e-02, -2.31762752e-02, -1.54952602e-02, -1.01982448e-02,
       -4.21378054e-02, -4.61890921e-02,  6.24677725e-02, -3.32370587e-02,
        7.09879771e-03,  1.37250107e-02, -5.07094711e-02, -7.40463007e-03,
        2.68303826e-02,  9.55260992e-02, -1.18887145e-02,  9.29567870e-03,
       -4.90151905e-02, -2.87848315e-03, -6.82504177e-02,  1.15289269e-02,
        4.30086516e-02,  4.68214005e-02,  9.59297083e-03,  3.46539877e-02,
        1.46428263e-02,  9.95147711e-05, -2.07786579e-02,  6.20696554e-03,
        2.86721401e-02, -8.71197879e-03,  1.96349155e-02,  4.83055115e-02,
        4.42702956e-02, -9.63991683e-04,  4.77366112e-02,  3.80587876e-02,
        4.33457680e-02, -9.15098004e-03, -2.78271250e-02, -3.37542146e-02,
        9.76962410e-03, -5.29775806e-02, -2.65057813e-02, -3.21314521e-02,
       -1.08620962e-02, -8.78769439e-03, -3.77236493e-02, -4.36700135e-03,
        2.26308182e-02,  1.88240930e-02,  3.58200110e-02,  3.96379549e-03,
       -1.58582982e-02, -5.25945462e-02,  1.46587407e-02, -1.22163966e-02,
        3.22133005e-02, -7.15218065e-03, -6.38930546e-03,  2.63522882e-02,
        3.53594795e-02,  6.56795222e-03, -4.36655879e-02, -2.16948260e-02,
        9.08679701e-03,  1.34848664e-02,  4.22448367e-02, -5.00409212e-03,
       -5.39222211e-02,  9.16399993e-03, -6.32131379e-03, -2.72621904e-02,
        3.72356288e-02, -2.20114067e-02, -4.05332968e-02, -4.26686332e-02,
       -1.70634370e-02, -5.07510900e-02,  5.56220338e-02, -2.89335679e-02,
        1.46721536e-02,  6.89766109e-02, -9.08626523e-03,  3.68878208e-02,
        1.61203500e-02,  2.12657563e-02,  4.96014319e-02,  2.17534397e-02,
       -1.67589560e-02,  4.75860666e-03,  1.80873871e-02, -3.37075368e-02,
        1.33492835e-02, -4.03909720e-02, -1.21677783e-03, -2.78581008e-02,
       -9.22292005e-03,  2.66369637e-02, -2.41954233e-02,  8.90766457e-03,
       -1.83374733e-02, -8.07688311e-02, -2.10528541e-02,  2.31335089e-02,
        3.80150415e-02, -1.15180323e-02, -1.36381183e-02,  1.48044676e-02,
       -3.54780741e-02, -3.69836465e-02, -2.46556606e-02, -3.32945748e-03,
        3.93160060e-02, -1.25067402e-02, -2.29575373e-02,  2.44600475e-02,
        6.62176916e-03,  1.55038470e-02,  1.06279282e-02,  1.88039280e-02,
       -4.78942953e-02,  3.22973076e-03, -3.75859067e-02,  3.89544629e-02,
       -2.05167215e-02,  2.99735237e-02, -4.45941987e-04, -4.46603028e-03,
       -7.34301377e-03, -2.32359692e-02, -2.24928390e-02,  9.09642130e-02,
        6.20557880e-03, -7.09042558e-03,  3.67731741e-03, -1.54916085e-02,
       -1.87942404e-02,  5.97978272e-02, -1.12311086e-02, -8.85446570e-05,
       -2.04868224e-02,  3.29624563e-02,  8.39435607e-02,  1.98288467e-02,
        7.67581165e-03, -4.32895310e-03,  4.17177491e-02,  2.88498253e-02,
       -3.59754860e-02, -2.72799339e-02, -4.74579260e-02,  7.82096535e-02],
      dtype=float32)

In [11]:
df

,chunk_id,num_sentences,pages,text,tokens,embedding
0,0,10,[2],Introduction to Data Science What is Data Scie...,216,"[0.031114045530557, 0.05847082287073101, -0.14..."
1,1,1,[2],Simple Definition: Let me give you a very simp...,38,"[0.07906869798898601, 0.048007845878601005, -0..."
2,2,16,[3],Why is Data Science Important? In today’s worl...,238,"[0.00119032501243, 0.088782802224159, -0.16663..."
3,3,14,[4],Why Should You Care About Data Science? High D...,248,"[0.009450176730751, 0.10970566421747201, -0.16..."
4,4,5,[4],or “What factors drive sales?”. In “Coders of ...,73,"[-0.048604991286993006, 0.033864941447973, -0...."
...,...,...,...,...,...,...
816,816,1,[432],Clear all stashes git stash clear # Show files...,50,"[0.04230986163020101, 0.0206143502146, -0.1448..."
817,817,2,[433],Create Branch from Stash Stash Specific Files ...,96,"[0.007109073456376001, 0.033814206719398006, -..."
818,818,1,[433],... git checkout feature-branch git stash pop ...,24,"[-0.015776261687278, 0.026989463716745002, -0...."
819,819,2,[434],Commands Summary Command Description git stash...,72,"[-0.000491104146931, 0.022059485316276002, -0...."
820,820,1,[434],[name] Create branch from stash CodeWithHarry,10,"[-0.011027893051505, -0.008593205362558, -0.15..."

In [32]:
def create_question_embedding(question):
    return model.encode(
        question,
        normalize_embeddings=True
    )


incoming_query="Why to learn Data Science?"
question_embedding = create_question_embedding(incoming_query)
embeddings_matrix = np.vstack(df["embedding"].values)
# np.save("embeddings.npy", embeddings_matrix)
# embeddings_matrix = np.load("embeddings.npy")
question_embedding = np.array(question_embedding).reshape(1, -1)
similarities=cosine_similarity(embeddings_matrix, question_embedding ).flatten()
top_results = 3
max_indx = similarities.argsort()[::-1][0:top_results]
print(max_indx)
new_df = df.loc[max_indx] 
print(new_df[["pages", "text", "chunk_id"]])
df=joblib.load("dataframe")

[0 3 2]
  pages                                               text  chunk_id
0   [2]  Introduction to Data Science What is Data Scie...         0
3   [4]  Why Should You Care About Data Science? High D...         3
2   [3]  Why is Data Science Important? In today’s worl...         2

In [33]:
df

,chunk_id,num_sentences,pages,text,tokens,embedding
0,0,10,[2],Introduction to Data Science What is Data Scie...,216,"[0.031114045530557, 0.05847082287073101, -0.14..."
1,1,1,[2],Simple Definition: Let me give you a very simp...,38,"[0.07906869798898601, 0.048007845878601005, -0..."
2,2,16,[3],Why is Data Science Important? In today’s worl...,238,"[0.00119032501243, 0.088782802224159, -0.16663..."
3,3,14,[4],Why Should You Care About Data Science? High D...,248,"[0.009450176730751, 0.10970566421747201, -0.16..."
4,4,5,[4],or “What factors drive sales?”. In “Coders of ...,73,"[-0.048604991286993006, 0.033864941447973, -0...."
...,...,...,...,...,...,...
816,816,1,[432],Clear all stashes git stash clear # Show files...,50,"[0.04230986163020101, 0.0206143502146, -0.1448..."
817,817,2,[433],Create Branch from Stash Stash Specific Files ...,96,"[0.007109073456376001, 0.033814206719398006, -..."
818,818,1,[433],... git checkout feature-branch git stash pop ...,24,"[-0.015776261687278, 0.026989463716745002, -0...."
819,819,2,[434],Commands Summary Command Description git stash...,72,"[-0.000491104146931, 0.022059485316276002, -0...."
820,820,1,[434],[name] Create branch from stash CodeWithHarry,10,"[-0.011027893051505, -0.008593205362558, -0.15..."